#!/usr/bin/env zsh
cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTOOTING_WARNING_AS_ERROR=OFF -DBUILD_GUI=OFF -DWITH_DEMOS=OFF-DWITH_INSTRUMENTS=OFF -DWITH_WAVETABLES=OFF -DSYSTEM_ZLIB=OFF -DSYSTEM_RTMIDI=OFF -DSYSTEM_FFTW=OFF -DSYSTEM_FMT=OFF -DSYSTEM_LIBSNDFILE=OFF -DSYSTEM_FREETYPE=OFF -DWITH_RENDER_OPENGL=OFF -DWITH_RENDER_SDL=OFF -DWITH_RENDER_DX9=OFF -DWITH_RENDER_DX11=OFF -DUSE_GLES=OFF -DUSE_SDL2=OFF
cmake --build build --parallel 8
