#!/usr/bin/env zsh
cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTOOTING_WARNING_AS_ERROR=OFF -DSYSTEM_ZLIB=OFF -DSYSTEM_RTMIDI=OFF -DSYSTEM_FFTW=OFF -DSYSTEM_FMT=OFF -DSYSTEM_LIBSNDFILE=OFF -DSYSTEM_FREETYPE=OFF
cmake --build build --parallel 8
